const sidebars = {
  dflareAi: [
    "dflare-ai/index",
    {
      type: "category",
      label: "Platform",
      collapsed: false,
      items: [
        "dflare-ai/platform/overview",
        "dflare-ai/platform/architecture",
        "dflare-ai/platform/security",
        "dflare-ai/platform/deployment",
      ],
    },
    {
      type: "category",
      label: "Services",
      collapsed: false,
      items: [
        "dflare-ai/services/bare-metal",
        "dflare-ai/services/kubernetes",
        "dflare-ai/services/slurm",
        "dflare-ai/services/storage",
        "dflare-ai/services/networking",
        "dflare-ai/services/identity",
        "dflare-ai/services/monitoring",
        "dflare-ai/services/billing",
      ],
    },
    {
      type: "category",
      label: "ML Platform",
      collapsed: false,
      items: [
        "dflare-ai/ml-platform/overview",
        "dflare-ai/ml-platform/notebooks",
        "dflare-ai/ml-platform/training",
        "dflare-ai/ml-platform/inference",
        "dflare-ai/ml-platform/fine-tuning",
        "dflare-ai/ml-platform/mlflow",
        "dflare-ai/ml-platform/evaluation",
        "dflare-ai/ml-platform/datasets",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsed: false,
      items: [
        "dflare-ai/services/integrations",
        "dflare-ai/platform/use-cases",
        "dflare-ai/platform/differentiators",
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsed: false,
      items: [
        "dflare-ai/resources/white-paper",
        "dflare-ai/resources/technical-guide",
        "dflare-ai/resources/integration-guides",
        "dflare-ai/resources/datasheets",
      ],
    },
  ],
  ccp: [
    "ccp/index",
    {
      type: "category",
      label: "Platform",
      collapsed: false,
      items: [
        "ccp/platform/overview",
        "ccp/platform/architecture",
        "ccp/platform/security",
        "ccp/platform/deployment",
        "ccp/platform/use-cases",
        "ccp/platform/differentiators",
      ],
    },
    {
      type: "category",
      label: "Services",
      collapsed: false,
      items: [
        "ccp/services/compute",
        "ccp/services/storage",
        "ccp/services/networking",
        "ccp/services/identity",
        "ccp/services/monitoring",
        "ccp/services/database",
        "ccp/services/security-services",
        "ccp/services/billing",
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsed: false,
      items: [
        "ccp/resources/whitepaper",
        "ccp/resources/datasheet",
        "ccp/resources/integration-design",
        "ccp/resources/functional-spec",
        "ccp/resources/product-user-guide",
        "ccp/resources/product-user-guide-1",
      ],
    },
  ],
  ckp: [
    "ckp/index",
    {
      type: "category",
      label: "Distribution",
      collapsed: false,
      items: [
        "ckp/distribution/overview",
        "ckp/distribution/images",
        "ckp/distribution/compatibility",
        "ckp/distribution/dependencies",
      ],
    },
    {
      type: "category",
      label: "Cluster Management",
      collapsed: false,
      items: [
        "ckp/cluster-management/creation",
        "ckp/cluster-management/upgrades",
        "ckp/cluster-management/lifecycle",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      collapsed: false,
      items: [
        "ckp/architecture/overview",
        "ckp/architecture/advantages",
      ],
    },
    {
      type: "category",
      label: "Infrastructure",
      collapsed: false,
      items: [
        "ckp/infrastructure/providers",
        "ckp/infrastructure/capi-integration",
      ],
    },
    {
      type: "category",
      label: "Components",
      collapsed: false,
      items: [
        "ckp/components/host-agent",
        "ckp/components/host-provisioner",
        "ckp/components/registry",
      ],
    },
    {
      type: "category",
      label: "APIs",
      collapsed: false,
      items: [
        "ckp/apis/machine-host",
        "ckp/apis/provider-cluster",
      ],
    },
    {
      type: "category",
      label: "Addons",
      collapsed: false,
      items: [
        "ckp/addons/autoscaling",
        "ckp/addons/storage",
        "ckp/addons/backup",
        "ckp/addons/certificates",
      ],
    },
    // {
    //   type: "category",
    //   label: "Operations",
    //   collapsed: false,
    //   items: [
    //     "ckp/operations/build-artifacts",
    //     "ckp/operations/troubleshooting",
    //     "ckp/operations/glossary",
    //   ],
    // },
    {
      type: "category",
      label: "Resources",
      collapsed: false,
      items: [
        "ckp/resources/white-paper",
        "ckp/resources/technical-guide",
        "ckp/resources/datasheet",
      ],
    },
  ],
  cloudOrbiter: [
    "cloud-orbiter/index",
    {
      type: "category",
      label: "Platform",
      collapsed: false,
      items: [
        "cloud-orbiter/platform/overview",
        "cloud-orbiter/platform/architecture",
        "cloud-orbiter/platform/security",
        "cloud-orbiter/platform/deployment",
        "cloud-orbiter/platform/use-cases",
        "cloud-orbiter/platform/differentiators",
      ],
    },
    {
      type: "category",
      label: "Services",
      collapsed: false,
      items: [
        "cloud-orbiter/services/clusters",
        "cloud-orbiter/services/kubernetes-engine",
        "cloud-orbiter/services/applications",
        "cloud-orbiter/services/observability",
        "cloud-orbiter/services/identity",
        "cloud-orbiter/services/backup-restore",
        "cloud-orbiter/services/virtual-machines",
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsed: false,
      items: [
        "cloud-orbiter/resources/product-user-guide",
        "cloud-orbiter/resources/datasheet",
        "cloud-orbiter/resources/whitepaper",
      ],
    },
  ],
  corobots: ["corobots/index"],
  cvm: ["cvm/index"],
  solutions: ["solutions/ai-ml"],
  developer: ["developer/api/index"],
};

module.exports = sidebars;
